name       : haskell-mime-types
version    : 0.1.0.9
release    : 3
source     :
    - https://hackage.haskell.org/package/mime-types-0.1.0.9/mime-types-0.1.0.9.tar.gz : 0a32435169ef4ba59f4a4b8addfd0c04479410854d1b8d69a1e38fb389ba71d2
license    : MIT
component  : programming.haskell
summary    : Basic mime-type handling types and functions
description: |
    Basic mime-type handling types and functions
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
