name       : haskell-mime-types
version    : 0.1.0.7
release    : 2
source     :
    - http://hackage.haskell.org/package/mime-types-0.1.0.7/mime-types-0.1.0.7.tar.gz : 83164a24963a7ef37543349df095155b30116c208e602a159a5cd3722f66e9b9
license    : MIT
component  : programming.haskell
summary    : Basic mime-type handling types and functions
description: |
    Basic mime-type handling types and functions
builddeps  :
    - haskell-cabal-install
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
